/* =====================================================================
   smartMOOV BI Catalogue — usage-ranked data layer
   Every report in the PEPCO Power BI workspace ranked by ACTUAL views
   (Usage Metrics Report, 6 Jun – 5 Jul 2026), classified Dashboard /
   Extract / Hybrid, with retirement candidates flagged. Detailed metric
   content is carried for the reports people actually open; the near-zero
   tail carries name + category + usage + delivery type only.
   GENERATED from the usage CSV — edit the generator, not this file.
   No PII: access-directory reports are catalogued by structure only.
   ===================================================================== */

window.MOOV = window.MOOV || {};

MOOV.bi = {
  "meta": {
    "client": "PEPCO",
    "system": "smartMOOV logistics hub — Power BI embedded reports (getBIReportUrl API)",
    "dataSource": "smartMOOV operational database",
    "refreshCadence": "4×/day at 08:30, 10:00, 13:30, 16:30 (UTC+8)",
    "usageWindow": "6 Jun – 5 Jul 2026",
    "usageSource": "Power BI Usage Metrics Report (read on screen)",
    "workspaceReportCount": 108,
    "cataloguedCount": 106,
    "totalViews": 12336,
    "viewers": [
      "c.marz",
      "itdev01",
      "l.ollie",
      "pepco_ba@moovlogistics.com"
    ],
    "viewTrend": "−1.2%",
    "typicalOpenTime": "~3 s",
    "purposeQuestions": [
      "What are we actually using?",
      "What's genuinely there for the client?",
      "What's just used as a data download?",
      "Where are the big datasets?"
    ],
    "calcNote": "DAX measure formulas are not browser-extractable. Calculation logic is either 'documented' (shown on the report's own Notes / KPI Definitions page) or 'inferred' from labels.",
    "caveats": [
      "View counts were read on screen from the Usage Metrics Report — treat single-digit counts as approximate.",
      "Only 4 users exist in this workspace, so “usage” is a small sample.",
      "PEPCO-scoped only: Lidl and other clients weren't visible under this login. Confirm access before treating this as the full picture.",
      "Workspace shows 108 active reports; 106 rows were legible in the usage report and are catalogued here."
    ],
    "usageTiers": {
      "workhorse": {
        "label": "Workhorses",
        "range": "> 400 views",
        "blurb": "Protect & keep as dashboards — these carry the operation.",
        "count": 7,
        "views": 7347
      },
      "regular": {
        "label": "Regular use",
        "range": "100–400 views",
        "blurb": "In steady use — keep, but watch the declining ones.",
        "count": 15,
        "views": 2392
      },
      "low": {
        "label": "Low use",
        "range": "20–100 views",
        "blurb": "Review value — is a dashboard still warranted?",
        "count": 55,
        "views": 2407
      },
      "near-zero": {
        "label": "Near-zero",
        "range": "< 20 views",
        "blurb": "Retirement / extract-only candidates — dashboards nobody opens.",
        "count": 29,
        "views": 190
      }
    },
    "deliveryTypes": {
      "Dashboard": "Charts / KPIs people read on screen.",
      "Extract": "Essentially a table people download to Excel — no dashboard maintenance needed.",
      "Hybrid": "Dashboard front page with a Raw Data page behind it — the team may only need the raw data."
    },
    "categories": [
      "Forecast",
      "General",
      "Booking",
      "Supplier",
      "Carrier",
      "ASN",
      "Operations",
      "Customs",
      "Destination",
      "Finance"
    ],
    "glossary": {
      "ATA": "Actual arrival at destination port",
      "ATD": "Actual departure from origin",
      "CFS": "Container freight station",
      "CRD": "Cargo ready date confirmed by supplier",
      "CY": "Container yard",
      "ETA": "Estimated time of arrival",
      "ETD": "Estimated time of departure",
      "HOD": "Merchandise cargo handover date per PEPCO PO",
      "PCRD": "Planned cargo ready date = 7 days before HOD",
      "AHOD": "Adjusted Handover Date",
      "OHA": "Origin Handling Agent",
      "SO Type": "Shipment order type (FCL / LCL)",
      "TEU": "Twenty-foot equivalent unit",
      "Week definitions": "Booked ETD Week, ETD Week (Mon–Sun, can update), ATD Week, Allocation Week, ETA Week"
    }
  },
  "reports": [
    {
      "id": "daily-booking-carrier",
      "rank": 1,
      "name": "Daily Booking Carrier",
      "category": "Booking",
      "views": 2627,
      "viewsPct": "21%",
      "users": 4,
      "activeDays": 28,
      "viewTrend": "+30%",
      "usageTier": "workhorse",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Daily carrier booking monitoring — the workspace's most-viewed report.",
      "granularity": "Order-level, daily",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "customs-broker-performance",
      "rank": 2,
      "name": "Customs Broker Performance",
      "category": "Customs",
      "views": 1139,
      "viewsPct": "9%",
      "users": 2,
      "activeDays": 29,
      "viewTrend": "-22%",
      "usageTier": "workhorse",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Customs broker clearance performance monitoring.",
      "granularity": "Broker / declaration-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "longterm-volume-forecast",
      "rank": 3,
      "name": "Longterm Volume Forecast",
      "category": "Forecast",
      "views": 1134,
      "viewsPct": "9%",
      "users": 3,
      "activeDays": 26,
      "viewTrend": "-2%",
      "usageTier": "workhorse",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Long-range TEU volume forecasting for capacity planning.",
      "pages": [
        "Overview",
        "Order Status Overview",
        "Raw Data",
        "Glossary",
        "Notes"
      ],
      "metrics": [
        "TEU by ETD Week (MOOV vs historical non-MOOV)",
        "Volume by Order Status"
      ],
      "visuals": [
        "TEU line chart by ETD Week",
        "Stacked bar by Order Status"
      ],
      "slicers": [
        "POL Region",
        "POL",
        "POD Region",
        "Merch Code",
        "Order Status",
        "Year",
        "SO Type"
      ],
      "granularity": "Order-level aggregated to ETD Week",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "midterm-volume-forecast-origin",
      "rank": 4,
      "name": "Midterm Volume Forecast - Origin",
      "category": "Forecast",
      "views": 809,
      "viewsPct": "7%",
      "users": 4,
      "activeDays": 25,
      "viewTrend": "+61%",
      "usageTier": "workhorse",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Mid-range origin-level volume forecast and carrier booking status.",
      "pages": [
        "Origin Overview",
        "Origin Overview (HOD Week)",
        "Carrier Booking Status"
      ],
      "metrics": [
        "Volume by Adjusted MFC ETD Week",
        "Carrier booking status breakdown"
      ],
      "visuals": [
        "Stacked bar by Adjusted MFC ETD Week",
        "Detail table"
      ],
      "slicers": [
        "Premium / Spot / Standard",
        "POL",
        "Carrier",
        "POL Region",
        "POD Region"
      ],
      "granularity": "Origin / order-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "ahod-reason-code",
      "rank": 5,
      "name": "AHOD Reason Code",
      "category": "Operations",
      "views": 728,
      "viewsPct": "6%",
      "users": 4,
      "activeDays": 25,
      "viewTrend": "+12%",
      "usageTier": "workhorse",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Analysis of adjusted-handover-date reason codes.",
      "pages": [
        "Overview",
        "Rawdata",
        "Glossary"
      ],
      "metrics": [
        "Total PO's with AHOD Reason by HOD Month",
        "Reason code distribution (FCL / LCL)"
      ],
      "visuals": [
        "Bar by HOD Month",
        "FCL/LCL pie by reason code (CD1, CD2, FM02, FM03, S01, V02, V03, V05, V06)"
      ],
      "sampleData": "FCL: V03 = 77.91%",
      "slicers": [
        "HOD Month",
        "Origin Country",
        "Origin Port",
        "SO Type",
        "ATD Month",
        "ATD Week"
      ],
      "granularity": "PO-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "destination-delivery-performance",
      "rank": 6,
      "name": "Destination Delivery Performance",
      "category": "Destination",
      "views": 475,
      "viewsPct": "4%",
      "users": 4,
      "activeDays": 29,
      "viewTrend": "-36%",
      "usageTier": "workhorse",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Destination-side delivery performance monitoring.",
      "granularity": "Delivery / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "destination-milestone-monitor",
      "rank": 7,
      "name": "Destination Milestone Monitor",
      "category": "Destination",
      "views": 435,
      "viewsPct": "4%",
      "users": 3,
      "activeDays": 23,
      "viewTrend": "+10%",
      "usageTier": "workhorse",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Live monitoring of destination milestones.",
      "granularity": "Milestone / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "daily-booking-supplier",
      "rank": 8,
      "name": "Daily Booking Supplier",
      "category": "Booking",
      "views": 329,
      "viewsPct": "3%",
      "users": 3,
      "activeDays": 27,
      "viewTrend": "-15%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Daily supplier booking monitoring.",
      "granularity": "Order-level, daily",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "allocation-management",
      "rank": 9,
      "name": "Allocation Management",
      "category": "Carrier",
      "views": 267,
      "viewsPct": "2%",
      "users": 2,
      "activeDays": 25,
      "viewTrend": "-24%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Carrier allocation planning and management.",
      "granularity": "Allocation Week / carrier-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "crd-and-in-dc-date-analysis",
      "rank": 10,
      "name": "CRD And In-DC Date Analysis",
      "category": "Operations",
      "views": 237,
      "viewsPct": "2%",
      "users": 3,
      "activeDays": 22,
      "viewTrend": "+15%",
      "usageTier": "regular",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Analysis of cargo ready dates vs in-DC arrival dates.",
      "granularity": "PO / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "container-utilization",
      "rank": 11,
      "name": "Container Utilization",
      "category": "Operations",
      "views": 190,
      "viewsPct": "2%",
      "users": 4,
      "activeDays": 22,
      "viewTrend": "-4%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Container fill efficiency / utilization analysis.",
      "pages": [
        "SI Overview",
        "SI Monthly Summary"
      ],
      "metrics": [
        "Container fill / utilization %"
      ],
      "visuals": [
        "Fill / utilization scatter",
        "Bar charts"
      ],
      "granularity": "Container-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "pbl-and-container-list",
      "rank": 12,
      "name": "PBL And Container List",
      "category": "Operations",
      "views": 178,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 19,
      "viewTrend": "-16%",
      "usageTier": "regular",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "PBL and container list — table extract.",
      "granularity": "Container-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "origin-kpi-report",
      "rank": 13,
      "name": "Origin KPI Report",
      "category": "Operations",
      "views": 157,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 19,
      "viewTrend": "+31%",
      "usageTier": "regular",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Origin-side milestone on-time performance across the pre-departure lifecycle.",
      "pages": [
        "Overview",
        "Weekly Overview",
        "Monthly Overview",
        "Raw Data",
        "KPI Definitions",
        "Glossary"
      ],
      "metrics": [
        "Booking Validation on-time",
        "Transport Preassign on-time",
        "SO Release to Supplier on-time",
        "AHOD Update on-time",
        "ATD Confirmation on-time",
        "Vessel Departure Confirmation on-time"
      ],
      "visuals": [
        "Six ONTIME / NOT-ONTIME donut charts"
      ],
      "slicers": [
        "ETD Year/Month",
        "Origin Point",
        "DC",
        "OHA",
        "SO Type"
      ],
      "granularity": "Origin / milestone-level",
      "calcBasis": "documented",
      "calcDetail": "On-Time = milestone completed within N working days of its trigger — Booking Validation within 1 working day of Shipper Booking; Transport Preassign within 1 working day of Booking Validation; SO Release to Supplier within 7 days after the booked slot; AHOD Update within 2 working days of actual AHOD; ATD Confirmation within 3 working days of actual ATD; Vessel Departure Confirmation within 2 days of actual ATD.",
      "detailLevel": "full"
    },
    {
      "id": "monthly-container-list-finance",
      "rank": 14,
      "name": "Monthly Container List - Finance",
      "category": "Finance",
      "views": 138,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "-52%",
      "usageTier": "regular",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Monthly container list for finance — table extract.",
      "granularity": "Container-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "weekly-closing",
      "rank": 15,
      "name": "Weekly Closing",
      "category": "Carrier",
      "views": 127,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "-24%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Weekly operational closing summary.",
      "granularity": "Weekly",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "report-user",
      "rank": 16,
      "name": "Report User",
      "category": "General",
      "views": 123,
      "viewsPct": "1%",
      "users": 4,
      "activeDays": 25,
      "viewTrend": "-22%",
      "usageTier": "regular",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Report access directory (who can view which report).",
      "pages": [
        "Pepco Report List",
        "PEPCO Report User"
      ],
      "metrics": [
        "Access mapping"
      ],
      "visuals": [
        "Access directory table (Category, Report Name, Nickname, Dept Name, Email)"
      ],
      "granularity": "User-level",
      "calcBasis": "n/a",
      "detailLevel": "full",
      "warning": "Contains personal data (emails). Catalogue structure only — no PII is extracted here."
    },
    {
      "id": "milestone-resubmit-analysis",
      "rank": 17,
      "name": "Milestone Resubmit Analysis",
      "category": "Supplier",
      "views": 115,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "-38%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Tracks supplier milestone resubmissions.",
      "granularity": "PO / milestone-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "booking-rejection-analysis",
      "rank": 18,
      "name": "Booking Rejection Analysis",
      "category": "Operations",
      "views": 113,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "-5%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of booking rejections over time.",
      "pages": [
        "Summary",
        "PEPCO Rejection Analysis"
      ],
      "metrics": [
        "Total Rejection by Month"
      ],
      "visuals": [
        "Total Rejection by Month bar",
        "KPI cards"
      ],
      "granularity": "Booking-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "inb-delivery-report",
      "rank": 19,
      "name": "INB Delivery Report",
      "category": "Destination",
      "views": 110,
      "viewsPct": "1%",
      "users": 2,
      "activeDays": 21,
      "viewTrend": "-66%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Inbound delivery report (destination).",
      "granularity": "Delivery-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "po-hod-analysis",
      "rank": 20,
      "name": "PO HOD Analysis",
      "category": "Supplier",
      "views": 110,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 24,
      "viewTrend": "-25%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of PO handover dates (HOD).",
      "granularity": "PO-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "transport-kpi-report",
      "rank": 21,
      "name": "Transport KPI Report",
      "category": "Destination",
      "views": 100,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 20,
      "viewTrend": "+22%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Destination transport KPI monitoring.",
      "granularity": "KPI / carrier-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "oha-management-bd",
      "rank": 22,
      "name": "OHA Management - BD",
      "category": "Operations",
      "views": 98,
      "viewsPct": "1%",
      "users": 2,
      "activeDays": 29,
      "viewTrend": "+80%",
      "usageTier": "regular",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Origin Handling Agent management — Bangladesh.",
      "granularity": "OHA / origin-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "destination-mot",
      "rank": 23,
      "name": "Destination MOT",
      "category": "Destination",
      "views": 97,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 20,
      "viewTrend": "+11%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Destination mode-of-transport analysis.",
      "granularity": "Order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "etd-and-eta-accuracy",
      "rank": 24,
      "name": "ETD And ETA Accuracy",
      "category": "Operations",
      "views": 90,
      "viewsPct": "1%",
      "users": 2,
      "activeDays": 20,
      "viewTrend": "-27%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Measures accuracy of estimated vs actual departure / arrival.",
      "pages": [
        "ETD-ETA Analysis",
        "Booked ETD-Booked ETA Analysis",
        "Booked ETA in the past",
        "ETD/ETA Measurement",
        "Before ATD monitor",
        "Glossary"
      ],
      "metrics": [
        "Transit-day distribution (% of total carrier bookings)",
        "POL-ETA Check: Y 18.72% / N 81.28%",
        "POD-ETA Check: Y 7.27% / N 92.73%"
      ],
      "visuals": [
        "Transit-day distribution buckets",
        "ETA check breakdowns"
      ],
      "tableColumns": [
        "Carrier Booking Ref",
        "POL",
        "POD",
        "Vessel",
        "Voyage",
        "ETD",
        "ETA",
        "ETD Allocation",
        "ETA Allocation"
      ],
      "slicers": [
        "Booking Status",
        "Turkey Shipment toggle"
      ],
      "granularity": "Carrier booking-level",
      "calcBasis": "documented",
      "detailLevel": "full"
    },
    {
      "id": "customs-clearance-atc-cargo",
      "rank": 25,
      "name": "Customs Clearance - ATC Cargo",
      "category": "Customs",
      "views": 88,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 24,
      "viewTrend": "-9%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Per-broker customs clearance monitor — ATC Cargo.",
      "granularity": "Declaration-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "monthly-volume-analysis-origin",
      "rank": 26,
      "name": "Monthly Volume Analysis - Origin",
      "category": "Operations",
      "views": 79,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "-9%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Monthly origin-level volume analysis.",
      "granularity": "Origin / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "oha-management-in",
      "rank": 27,
      "name": "OHA Management - IN",
      "category": "Operations",
      "views": 76,
      "viewsPct": "1%",
      "users": 4,
      "activeDays": 19,
      "viewTrend": "-19%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Origin Handling Agent management — India.",
      "granularity": "OHA / origin-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "pending-telex-monitor",
      "rank": 28,
      "name": "Pending TELEX Monitor",
      "category": "Operations",
      "views": 75,
      "viewsPct": "1%",
      "users": 2,
      "activeDays": 20,
      "viewTrend": "+8%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Monitoring of pending TELEX release.",
      "granularity": "Booking-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "destination-demurrage-and-detention-tracker",
      "rank": 29,
      "name": "Destination Demurrage & Detention Tracker",
      "category": "Destination",
      "views": 70,
      "viewsPct": "1%",
      "users": 4,
      "activeDays": 20,
      "viewTrend": "-15%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Destination demurrage and detention tracking.",
      "granularity": "Container-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "supplier-scorecard",
      "rank": 30,
      "name": "Supplier Scorecard",
      "category": "Supplier",
      "views": 70,
      "viewsPct": "1%",
      "users": 4,
      "activeDays": 17,
      "viewTrend": "-37%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Supplier timeliness scorecard across the PO lifecycle.",
      "pages": [
        "PO Timeliness Overview",
        "PO Rejection",
        "PO Timeliness (detail)"
      ],
      "metrics": [
        "Timely Shipper Booking Submission (~0.02% not on-time)",
        "Timely SI/VGM Submit (~47% not on-time)",
        "Timely Container Loading Result (~35% not on-time)",
        "Timely Upload Shipping Document (~35% not on-time)",
        "Milestone On-Time Ratio (trend)"
      ],
      "visuals": [
        "Four timeliness bars (% of total PO)",
        "Milestone On-Time Ratio line chart"
      ],
      "slicers": [
        "Supplier Name",
        "POL",
        "POD",
        "ATD Week"
      ],
      "granularity": "Supplier / PO-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "transport-carrier-delivery-on-time",
      "rank": 31,
      "name": "Transport Carrier Delivery on Time",
      "category": "Destination",
      "views": 70,
      "viewsPct": "1%",
      "users": 4,
      "activeDays": 19,
      "viewTrend": "+41%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "On-time delivery performance of inland transport carriers.",
      "granularity": "Carrier / delivery-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "longterm-volume-forecast-bd",
      "rank": 32,
      "name": "Longterm Volume Forecast - BD",
      "category": "Forecast",
      "views": 68,
      "viewsPct": "1%",
      "users": 2,
      "activeDays": 28,
      "viewTrend": "-0%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Per-country split of the Longterm Volume Forecast — Bangladesh.",
      "granularity": "Order-level aggregated to ETD Week",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "monthly-volume-analysis-origin-2",
      "rank": 33,
      "name": "Monthly Volume Analysis - Origin",
      "category": "Operations",
      "views": 67,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "+39%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Monthly origin-level volume analysis.",
      "granularity": "Origin / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "oha-management-in-2",
      "rank": 34,
      "name": "OHA Management - IN",
      "category": "Operations",
      "views": 64,
      "viewsPct": "1%",
      "users": 3,
      "activeDays": 21,
      "viewTrend": "+74%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Origin Handling Agent management — India.",
      "granularity": "OHA / origin-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "unplan-and-replan-analysis",
      "rank": 35,
      "name": "Unplan & Replan Analysis",
      "category": "Operations",
      "views": 63,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 21,
      "viewTrend": "+7%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of unplanned and replanned orders.",
      "granularity": "Order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "extract-po-list",
      "rank": 36,
      "name": "Extract PO List",
      "category": "Operations",
      "views": 62,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 22,
      "viewTrend": "+7%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Raw PO list extract.",
      "granularity": "PO-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "longterm-volume-forecast-destination",
      "rank": 37,
      "name": "Longterm Volume Forecast - Destination",
      "category": "Forecast",
      "views": 58,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 22,
      "viewTrend": "-65%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Destination-side view of the Longterm Volume Forecast.",
      "granularity": "Order-level aggregated to ETA Week",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "midterm-volume-forecast-destination",
      "rank": 38,
      "name": "Midterm Volume Forecast - Destination",
      "category": "Forecast",
      "views": 58,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 19,
      "viewTrend": "+5%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Destination-side view of the Midterm Volume Forecast.",
      "granularity": "Destination / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "po-milestone-performance",
      "rank": 39,
      "name": "PO Milestone Performance",
      "category": "Operations",
      "views": 58,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 17,
      "viewTrend": "+15%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "PO milestone completion performance by origin country and supplier.",
      "pages": [
        "Overview",
        "Overview 2",
        "CRD Submit",
        "Container Loading Result",
        "Dimensions",
        "Vessel Departure",
        "Shipper Booking",
        "Shipper Booking Validation",
        "Raw Data",
        "Glossary"
      ],
      "metrics": [
        "When it was possible / urgent / overdue (counts)",
        "Total PO's",
        "On-Time %",
        "Avg Days Overdue Before Completion"
      ],
      "visuals": [
        "Table by Country (BD, CN, IN, KE, KH, PK, TR, VN, Total)",
        "On-time pie",
        "Top 10 Impact Supplier table"
      ],
      "slicers": [
        "Country",
        "Supplier",
        "Milestone"
      ],
      "granularity": "PO / milestone-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "carrier-performance",
      "rank": 40,
      "name": "Carrier Performance",
      "category": "Carrier",
      "views": 57,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 17,
      "viewTrend": "-58%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Carrier schedule integrity and transit-time performance.",
      "pages": [
        "Schedule Integrity (Origin)",
        "Carrier Booked TEU Summary - Pepco",
        "Weekly Summary",
        "Scorecard"
      ],
      "metrics": [
        "Average Departure Delay (Days) = 1.82",
        "Average Arrival Delay (Days) = 5.81"
      ],
      "visuals": [
        "Booked vs Actual Transit Time chart",
        "KPI cards"
      ],
      "slicers": [
        "Carrier (CMDU, COSU, EGLV, HLCU, MAEU, MSCU)",
        "POL"
      ],
      "granularity": "Carrier / booking-level",
      "calcBasis": "documented",
      "calcDetail": "Departure Delay = ATD − Booked ETD; Arrival Delay = ATA − Booked ETA; averaged in days.",
      "detailLevel": "full"
    },
    {
      "id": "pending-po-monitoring",
      "rank": 41,
      "name": "Pending PO Monitoring",
      "category": "Operations",
      "views": 57,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 15,
      "viewTrend": "+238%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Monitoring of pending POs.",
      "granularity": "PO-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "docs-ready-analysis",
      "rank": 42,
      "name": "Docs Ready Analysis",
      "category": "Operations",
      "views": 53,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 22,
      "viewTrend": "+21%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of document readiness.",
      "granularity": "PO / document-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "dimension-data-extract",
      "rank": 43,
      "name": "Dimension Data Extract",
      "category": "Operations",
      "views": 49,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 20,
      "viewTrend": "+13%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Raw dimension data extract.",
      "granularity": "Item-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "customs-broker-performance-v2",
      "rank": 44,
      "name": "Customs Broker Performance - V2",
      "category": "Customs",
      "views": 47,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 18,
      "viewTrend": "-32%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "V2 of the customs broker performance report.",
      "granularity": "Broker / declaration-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "in-dc-date-eta",
      "rank": 45,
      "name": "In DC Date - ETA",
      "category": "Operations",
      "views": 45,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 14,
      "viewTrend": "-13%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "In-DC date vs ETA analysis.",
      "granularity": "Order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "insight-invoices-analysis",
      "rank": 46,
      "name": "Insight Invoices Analysis",
      "category": "Finance",
      "views": 44,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 18,
      "viewTrend": "-9%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Invoice insight analysis.",
      "granularity": "Invoice-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "customs-clearance-finished-analysis",
      "rank": 47,
      "name": "Customs Clearance Finished Analysis",
      "category": "Customs",
      "views": 41,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 18,
      "viewTrend": "-63%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of completed customs clearances.",
      "granularity": "Declaration-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "destination-milestone-detail-extract-internal",
      "rank": 48,
      "name": "Destination Milestone Detail Extract - Internal",
      "category": "Destination",
      "views": 40,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 14,
      "viewTrend": "-40%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Internal detail extract of destination milestones.",
      "granularity": "Milestone-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "planning-reason-analysis",
      "rank": 49,
      "name": "Planning Reason Analysis",
      "category": "Operations",
      "views": 40,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 15,
      "viewTrend": "+123%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of planning reason codes.",
      "granularity": "Order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "special-categories",
      "rank": 50,
      "name": "Special Categories",
      "category": "Operations",
      "views": 40,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 16,
      "viewTrend": "+35%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of special merchandise categories.",
      "granularity": "PO / item-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "supplier-performance-tracking",
      "rank": 51,
      "name": "Supplier Performance Tracking",
      "category": "Supplier",
      "views": 40,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 14,
      "viewTrend": "-5%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Ongoing tracking of supplier performance.",
      "granularity": "Supplier / PO-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "customs-clearance-gaston-schul",
      "rank": 52,
      "name": "Customs Clearance - Gaston Schul",
      "category": "Customs",
      "views": 37,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 15,
      "viewTrend": "-36%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Per-broker customs clearance monitor — Gaston Schul.",
      "granularity": "Declaration-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "pep5-report",
      "rank": 53,
      "name": "PEP5 Report",
      "category": "Operations",
      "views": 35,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 14,
      "viewTrend": "-43%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "PEP5 reference / admin extract.",
      "granularity": "Reference-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "shipping-document-verification-analysis",
      "rank": 54,
      "name": "Shipping Document Verification Analysis",
      "category": "Supplier",
      "views": 35,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 15,
      "viewTrend": "-25%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Verification analysis of supplier shipping documents.",
      "granularity": "PO / document-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "supplier-performance",
      "rank": 55,
      "name": "Supplier Performance",
      "category": "Supplier",
      "views": 35,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 13,
      "viewTrend": "-35%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Supplier on-time performance across key submission milestones.",
      "pages": [
        "Overview",
        "Christmas",
        "Christmas Analysis",
        "Raw Data"
      ],
      "metrics": [
        "Submit CRD Performance (49.86% not on-time)",
        "Submit Dimension Performance (40.79% not on-time)",
        "1st Booking Submission (15.92% not on-time)",
        "Document Upload (29.19% not on-time)"
      ],
      "visuals": [
        "Four ONTIME / NOT-ONTIME donut charts"
      ],
      "slicers": [
        "Supplier Name",
        "Origin Country",
        "Destination Port",
        "HOD Year/Month",
        "Shipping Type",
        "PILOT PO?"
      ],
      "granularity": "Supplier / PO-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "outbound-asn-log",
      "rank": 56,
      "name": "Outbound ASN Log",
      "category": "ASN",
      "views": 30,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 14,
      "viewTrend": "+17%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Advance Shipping Notice outbound log (raw extract).",
      "granularity": "Shipment-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "destination-milestone",
      "rank": 57,
      "name": "Destination Milestone",
      "category": "Destination",
      "views": 29,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 17,
      "viewTrend": "-55%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Destination milestone tracking.",
      "granularity": "Milestone / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "free-time-customs",
      "rank": 58,
      "name": "Free Time - Customs",
      "category": "Customs",
      "views": 29,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 10,
      "viewTrend": "-79%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Customs-side free time (detention / demurrage) analysis.",
      "granularity": "Container-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "freight-invoices-analysis-v2",
      "rank": 59,
      "name": "Freight Invoices Analysis - V2",
      "category": "Finance",
      "views": 28,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 17,
      "viewTrend": "-13%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Freight invoice analysis (V2).",
      "granularity": "Invoice-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "monthly-volume-analysis-destination",
      "rank": 60,
      "name": "Monthly Volume Analysis - Destination",
      "category": "Operations",
      "views": 27,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 13,
      "viewTrend": "+25%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Monthly destination-level volume analysis.",
      "granularity": "Destination / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "seasonal-promo-tracker",
      "rank": 61,
      "name": "Seasonal Promo Tracker",
      "category": "Operations",
      "views": 26,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 11,
      "viewTrend": "+40%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Tracks seasonal / promotional volume and readiness.",
      "granularity": "PO / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "transship-port-performance",
      "rank": 62,
      "name": "Transship Port Performance",
      "category": "Carrier",
      "views": 26,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 17,
      "viewTrend": "-27%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Transshipment port performance analysis.",
      "granularity": "Port / booking-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "longterm-volume-forecast-pk",
      "rank": 63,
      "name": "Longterm Volume Forecast - PK",
      "category": "Forecast",
      "views": 25,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 14,
      "viewTrend": "-8%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Per-country split of the Longterm Volume Forecast — Pakistan.",
      "granularity": "Order-level aggregated to ETD Week",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "sla-report",
      "rank": 64,
      "name": "SLA Report",
      "category": "Operations",
      "views": 25,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 9,
      "viewTrend": "+157%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Service-level compliance across OHA and supplier KPIs.",
      "pages": [
        "OHA KPI",
        "Supplier"
      ],
      "metrics": [
        "Color-coded compliance % by KPI category / metric / origin country"
      ],
      "visuals": [
        "Large KPI matrix (monthly + weekly columns), color-coded compliance %"
      ],
      "granularity": "KPI / origin-country-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "customs-clearance-vv-log",
      "rank": 65,
      "name": "Customs Clearance - VV-LOG",
      "category": "Customs",
      "views": 24,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 12,
      "viewTrend": "-15%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Per-broker customs clearance monitor — VV-LOG.",
      "granularity": "Declaration-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "po-milestone-change",
      "rank": 66,
      "name": "PO Milestone Change",
      "category": "Supplier",
      "views": 24,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 11,
      "viewTrend": "-3%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Tracks changes to PO milestones over time.",
      "granularity": "PO / milestone-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "supplier-user",
      "rank": 67,
      "name": "Supplier User",
      "category": "Supplier",
      "views": 24,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 13,
      "viewTrend": "+18%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Supplier user access directory.",
      "granularity": "User-level",
      "calcBasis": "n/a",
      "detailLevel": "structural",
      "warning": "Likely contains personal data; catalogue structure only."
    },
    {
      "id": "free-time-and-preferred-routing",
      "rank": 68,
      "name": "Free Time and Preferred Routing",
      "category": "Carrier",
      "views": 22,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 13,
      "viewTrend": "-5%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Free-time (detention / demurrage) and preferred routing analysis.",
      "granularity": "Lane / carrier-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "customs-extract",
      "rank": 69,
      "name": "Customs Extract",
      "category": "Customs",
      "views": 20,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 13,
      "viewTrend": "-76%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Raw customs data extract.",
      "granularity": "Declaration-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "scoring",
      "rank": 70,
      "name": "Scoring",
      "category": "Operations",
      "views": 19,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 11,
      "viewTrend": "-60%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Composite scoring analysis.",
      "granularity": "Order / entity-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "carrier-scoring",
      "rank": 71,
      "name": "Carrier Scoring",
      "category": "Carrier",
      "views": 19,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 12,
      "viewTrend": "-6%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Composite carrier scoring across reliability dimensions.",
      "pages": [
        "Overview",
        "Carrier Scoring",
        "Glossary"
      ],
      "metrics": [
        "Ontime (0–10)",
        "Speed (0–10)",
        "Capacity, reliability and flexibility (0–10)",
        "Variability"
      ],
      "visuals": [
        "Scoring table by carrier (TSHG, ONEY, MSCU, MAEU, HLCU, EGLV, COSU, CMDU)"
      ],
      "sampleData": "Totals: Ontime 6.24 / Speed 3.57 / Capacity 8.10 / Variability 2.22",
      "slicers": [
        "ATD Year (2025, 2026)",
        "ATD Month (01–06)"
      ],
      "granularity": "Carrier-level",
      "calcBasis": "inferred",
      "detailLevel": "full"
    },
    {
      "id": "latest-delivery-date",
      "rank": 72,
      "name": "Latest Delivery Date",
      "category": "Destination",
      "views": 18,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 12,
      "viewTrend": "-36%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Latest delivery date tracking.",
      "granularity": "Order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "longterm-volume-forecast-vn",
      "rank": 73,
      "name": "Longterm Volume Forecast - VN",
      "category": "Forecast",
      "views": 18,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 11,
      "viewTrend": "-36%",
      "usageTier": "low",
      "deliveryType": "Hybrid",
      "retirement": "no",
      "hasRawDataPage": true,
      "purpose": "Per-country split of the Longterm Volume Forecast — Vietnam.",
      "granularity": "Order-level aggregated to ETD Week",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "po-change-analysis",
      "rank": 74,
      "name": "PO Change Analysis",
      "category": "Operations",
      "views": 18,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 12,
      "viewTrend": "-25%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Analysis of PO changes over time.",
      "granularity": "PO-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "shipment-list",
      "rank": 75,
      "name": "Shipment List",
      "category": "Operations",
      "views": 17,
      "viewsPct": "0%",
      "users": 4,
      "activeDays": 9,
      "viewTrend": "+15%",
      "usageTier": "low",
      "deliveryType": "Extract",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Raw shipment list extract.",
      "granularity": "Shipment-level",
      "calcBasis": "n/a",
      "detailLevel": "structural"
    },
    {
      "id": "emissions",
      "rank": 76,
      "name": "Emissions",
      "category": "Operations",
      "views": 16,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 11,
      "viewTrend": "+50%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Container-level CO₂ emissions reporting.",
      "pages": [
        "Summary",
        "Glossary"
      ],
      "metrics": [
        "CO₂ emissions per container"
      ],
      "visuals": [
        "Container-level CO₂ table"
      ],
      "tableColumns": [
        "Carrier Booking Ref",
        "Container No",
        "Container Type",
        "Carrier",
        "Mode of transport",
        "ATA at POD",
        "Date of delivery to DC",
        "Weight of goods (kg)",
        "Distance"
      ],
      "granularity": "Container-level",
      "calcBasis": "inferred",
      "calcDetail": "Emissions ≈ weight × distance (GLEC-style emissions factor).",
      "detailLevel": "full"
    },
    {
      "id": "stock-on-water",
      "rank": 77,
      "name": "Stock On Water",
      "category": "Operations",
      "views": 15,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 11,
      "viewTrend": "-35%",
      "usageTier": "low",
      "deliveryType": "Dashboard",
      "retirement": "no",
      "hasRawDataPage": false,
      "purpose": "Cargo currently on the water (in transit).",
      "granularity": "Container / order-level",
      "calcBasis": "inferred",
      "detailLevel": "structural"
    },
    {
      "id": "eta-data-accuracy",
      "rank": 78,
      "name": "ETA Data Accuracy",
      "category": "Operations",
      "views": 13,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 10,
      "viewTrend": "-14%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "milestone-performance-destination",
      "rank": 79,
      "name": "Milestone Performance - Destination",
      "category": "Destination",
      "views": 13,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 10,
      "viewTrend": "-38%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-gaston-schul-internal",
      "rank": 80,
      "name": "Customs Clearance - Gaston Schul - Internal",
      "category": "Customs",
      "views": 12,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 9,
      "viewTrend": "-50%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "po-milestone",
      "rank": 81,
      "name": "PO Milestone",
      "category": "Operations",
      "views": 12,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 10,
      "viewTrend": "-3%",
      "usageTier": "near-zero",
      "deliveryType": "Hybrid",
      "retirement": "yes",
      "hasRawDataPage": true,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "procurement-report",
      "rank": 82,
      "name": "Procurement Report",
      "category": "Carrier",
      "views": 12,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 9,
      "viewTrend": "-67%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-dp-world",
      "rank": 83,
      "name": "Customs Clearance - DP World",
      "category": "Customs",
      "views": 11,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 7,
      "viewTrend": "-82%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "early-arrival-analysis",
      "rank": 84,
      "name": "Early Arrival Analysis",
      "category": "Operations",
      "views": 10,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 7,
      "viewTrend": "-5%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-gaston-schul-arola",
      "rank": 85,
      "name": "Customs Clearance - Gaston Schul - Arola",
      "category": "Customs",
      "views": 9,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 5,
      "viewTrend": "+25%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "early-arrival-analysis-container-level",
      "rank": 86,
      "name": "Early Arrival Analysis - Container Level",
      "category": "Operations",
      "views": 9,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 5,
      "viewTrend": "+25%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "manual-approval-analysis",
      "rank": 87,
      "name": "Manual Approval Analysis",
      "category": "Operations",
      "views": 9,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 7,
      "viewTrend": "-33%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "oha-management-vn",
      "rank": 88,
      "name": "OHA Management - VN",
      "category": "Operations",
      "views": 9,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 6,
      "viewTrend": "-40%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-kandn-medium",
      "rank": 89,
      "name": "Customs Clearance - K&N Medium",
      "category": "Customs",
      "views": 8,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 7,
      "viewTrend": "-40%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-ligentia",
      "rank": 90,
      "name": "Customs Clearance - Ligentia",
      "category": "Customs",
      "views": 8,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 6,
      "viewTrend": "-40%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "oha-management-kh",
      "rank": 91,
      "name": "OHA Management - KH",
      "category": "Operations",
      "views": 7,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 7,
      "viewTrend": "-33%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-customs-support",
      "rank": 92,
      "name": "Customs Clearance - Customs Support",
      "category": "Customs",
      "views": 6,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 3,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-ib-cargo",
      "rank": 93,
      "name": "Customs Clearance - IB Cargo",
      "category": "Customs",
      "views": 6,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 3,
      "viewTrend": "-50%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "customs-clearance-pepco-in-house-brokers",
      "rank": 94,
      "name": "Customs Clearance - Pepco In-house brokers",
      "category": "Customs",
      "views": 6,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 5,
      "viewTrend": "-80%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "freightower-transit-leg-extract",
      "rank": 95,
      "name": "Freightower Transit Leg Extract",
      "category": "Operations",
      "views": 6,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 4,
      "viewTrend": "-25%",
      "usageTier": "near-zero",
      "deliveryType": "Extract",
      "retirement": "review",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "n/a"
    },
    {
      "id": "customs-clearance-mpu",
      "rank": 96,
      "name": "Customs Clearance - MPU",
      "category": "Customs",
      "views": 4,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 3,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "historical-eta",
      "rank": 97,
      "name": "Historical ETA",
      "category": "Operations",
      "views": 4,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 4,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "longterm-volume-forecast-kh",
      "rank": 98,
      "name": "Longterm Volume Forecast - KH",
      "category": "Forecast",
      "views": 3,
      "viewsPct": "0%",
      "users": 3,
      "activeDays": 4,
      "viewTrend": "-50%",
      "usageTier": "near-zero",
      "deliveryType": "Hybrid",
      "retirement": "yes",
      "hasRawDataPage": true,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "oha-management",
      "rank": 99,
      "name": "OHA Management",
      "category": "Operations",
      "views": 3,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 2,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "daily-booking-oncarriage",
      "rank": 100,
      "name": "Daily Booking Oncarriage",
      "category": "Booking",
      "views": 2,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 2,
      "viewTrend": "0%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "predictive-eta",
      "rank": 101,
      "name": "Predictive ETA",
      "category": "Operations",
      "views": 2,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 2,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "oha-management-tr",
      "rank": 102,
      "name": "OHA Management - TR",
      "category": "Operations",
      "views": 2,
      "viewsPct": "0%",
      "users": 2,
      "activeDays": 2,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "chinese-new-year",
      "rank": 103,
      "name": "Chinese New Year",
      "category": "Operations",
      "views": 1,
      "viewsPct": "0%",
      "users": 1,
      "activeDays": 1,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "consolidation-simulation",
      "rank": 104,
      "name": "Consolidation Simulation",
      "category": "Operations",
      "views": 1,
      "viewsPct": "0%",
      "users": 1,
      "activeDays": 1,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Dashboard",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "longterm-volume-forecast-tr",
      "rank": 105,
      "name": "Longterm Volume Forecast - TR",
      "category": "Forecast",
      "views": 1,
      "viewsPct": "0%",
      "users": 1,
      "activeDays": 1,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Hybrid",
      "retirement": "yes",
      "hasRawDataPage": true,
      "detailLevel": "structural",
      "calcBasis": "inferred"
    },
    {
      "id": "sheet1",
      "rank": 106,
      "name": "sheet1",
      "category": "Operations",
      "views": 1,
      "viewsPct": "0%",
      "users": 1,
      "activeDays": 1,
      "viewTrend": "-100%",
      "usageTier": "near-zero",
      "deliveryType": "Extract",
      "retirement": "yes",
      "hasRawDataPage": false,
      "detailLevel": "structural",
      "calcBasis": "n/a"
    }
  ]
};

/* --- helpers -------------------------------------------------------- */
MOOV.bi.reportById = function (id) {
  return MOOV.bi.reports.find((r) => r.id === id) || null;
};
MOOV.bi.isBigDataset = function (r) {
  return r.deliveryType === "Extract" || r.hasRawDataPage;
};
