/* =====================================================================
   smartMOOV BI Catalogue — data layer
   Catalogue of PEPCO's Power BI embedded reports in the smartMOOV
   logistics hub. Structure captured from the live reports; DAX measure
   formulas are NOT browser-extractable, so calculation logic is either
   "documented" (shown on a report's own Notes / KPI Definitions page) or
   "inferred" from labels. No PII is stored here — access-directory
   reports are catalogued by structure only.
   ===================================================================== */

window.MOOV = window.MOOV || {};

MOOV.bi = {
  meta: {
    client: "PEPCO",
    system: "smartMOOV logistics hub — Power BI embedded reports (getBIReportUrl API)",
    dataSource: "smartMOOV operational database",
    refreshCadence: "4×/day at 08:30, 10:00, 13:30, 16:30 (UTC+8)",
    dataScope: "Order-level; excludes cancelled orders",
    calcNote:
      "DAX measure formulas are not browser-extractable. Calculation logic is either 'documented' (shown on the report's own Notes / KPI Definitions page) or 'inferred' from labels.",
    pepcoVariantNote:
      "Reports suffixed “- Pepco” are client-styled alternate layouts of the same underlying dataset.",
    categories: ["Forecast", "General", "Booking", "Supplier", "Carrier", "ASN", "Operations"],
    tiers: {
      1: {
        label: "Operational core",
        blurb:
          "Daily decision-making — on-time delivery, carrier/supplier accountability, capacity and SLA. The metrics a logistics control tower lives on.",
      },
      2: {
        label: "Supporting analysis",
        blurb: "Weekly / tactical analysis that informs planning but isn't watched hour to hour.",
      },
      3: {
        label: "Raw extracts & admin",
        blurb: "Reference and ops-support extracts, plus access directories.",
      },
    },
    glossary: {
      ATA: "Actual arrival at destination port",
      ATD: "Actual departure from origin",
      CFS: "Container freight station",
      CRD: "Cargo ready date confirmed by supplier",
      CY: "Container yard",
      ETA: "Estimated time of arrival",
      ETD: "Estimated time of departure",
      HOD: "Merchandise cargo handover date per PEPCO PO",
      PCRD: "Planned cargo ready date = 7 days before HOD",
      AHOD: "Adjusted Handover Date",
      OHA: "Origin Handling Agent",
      "SO Type": "Shipment order type (FCL / LCL)",
      TEU: "Twenty-foot equivalent unit",
      "Week definitions": "Booked ETD Week, ETD Week (Mon–Sun, can update), ATD Week, Allocation Week, ETA Week",
    },
    orderStatusCategories: [
      "Carrier Booking (Onboard)",
      "Carrier Booking (Released)",
      "Carrier Booking (Not Released)",
      "No Carrier Booking",
      "Pre-Assigned (With Score) No Carrier Booking",
      "Pre-Assigned (Without Score) No Carrier Booking",
      "Supplier Booking No Schedule Pre-Assigned",
      "CRD Set No Supplier Booking",
      "No CRD Set",
    ],
  },

  /* --- 67 reports across 7 categories -------------------------------- */
  reports: [
    /* ===================== FORECAST (2) ===================== */
    {
      id: "longterm-volume-forecast",
      name: "PEPCO Longterm Volume Forecast",
      category: "Forecast",
      tier: 1,
      purpose: "Long-range TEU volume forecasting for capacity planning.",
      pages: ["Overview", "Order Status Overview", "Raw Data", "Glossary", "Notes"],
      metrics: ["TEU by ETD Week (MOOV vs historical non-MOOV)", "Volume by Order Status"],
      visuals: ["TEU line chart by ETD Week", "Stacked bar by Order Status"],
      slicers: ["POL Region", "POL", "POD Region", "Merch Code", "Order Status", "Year", "SO Type"],
      granularity: "Order-level aggregated to ETD Week",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "midterm-volume-forecast-origin",
      name: "PEPCO Midterm Volume Forecast - Origin",
      category: "Forecast",
      tier: 1,
      purpose: "Mid-range origin-level volume forecast and carrier booking status.",
      pages: ["Origin Overview", "Origin Overview (HOD Week)", "Carrier Booking Status"],
      metrics: ["Volume by Adjusted MFC ETD Week", "Carrier booking status breakdown"],
      visuals: ["Stacked bar by Adjusted MFC ETD Week", "Detail table"],
      slicers: ["Premium / Spot / Standard", "POL", "Carrier", "POL Region", "POD Region"],
      granularity: "Origin / order-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },

    /* ===================== GENERAL (1) ===================== */
    {
      id: "report-user",
      name: "PEPCO Report User",
      category: "General",
      tier: 3,
      purpose: "Report access directory (who can view which report).",
      pages: ["Pepco Report List", "PEPCO Report User"],
      metrics: ["Access mapping"],
      visuals: ["Access directory table (Category, Report Name, Nickname, Dept Name, Email)"],
      slicers: [],
      granularity: "User-level",
      calcBasis: "n/a",
      detailLevel: "full",
      warning: "Contains personal data (emails). Catalogue structure only — no PII is extracted here.",
    },

    /* ===================== BOOKING (3) ===================== */
    {
      id: "daily-booking-carrier",
      name: "PEPCO Daily Booking-Carrier Booking",
      category: "Booking",
      tier: 2,
      purpose: "Daily carrier booking monitoring.",
      granularity: "Order-level, daily",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "daily-booking-carrier-pepco",
      name: "PEPCO Daily Booking-Carrier Booking - Pepco",
      category: "Booking",
      tier: 2,
      purpose: "Client-styled layout of Daily Booking-Carrier Booking.",
      granularity: "Order-level, daily",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "daily-booking-carrier",
    },
    {
      id: "daily-booking-supplier",
      name: "PEPCO Daily Booking-Supplier Booking",
      category: "Booking",
      tier: 2,
      purpose: "Daily supplier booking monitoring.",
      granularity: "Order-level, daily",
      calcBasis: "inferred",
      detailLevel: "structural",
    },

    /* ===================== SUPPLIER (7) ===================== */
    {
      id: "supplier-performance",
      name: "PEPCO Supplier Performance",
      category: "Supplier",
      tier: 1,
      purpose: "Supplier on-time performance across key submission milestones.",
      pages: ["Overview", "Christmas", "Christmas Analysis", "Raw Data"],
      metrics: [
        "Submit CRD Performance (49.86% not on-time)",
        "Submit Dimension Performance (40.79% not on-time)",
        "1st Booking Submission (15.92% not on-time)",
        "Document Upload (29.19% not on-time)",
      ],
      visuals: ["Four ONTIME / NOT-ONTIME donut charts"],
      slicers: ["Supplier Name", "Origin Country", "Destination Port", "HOD Year/Month", "Shipping Type", "PILOT PO?"],
      granularity: "Supplier / PO-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "supplier-scorecard",
      name: "PEPCO Supplier Scorecard",
      category: "Supplier",
      tier: 1,
      purpose: "Supplier timeliness scorecard across the PO lifecycle.",
      pages: ["PO Timeliness Overview", "PO Rejection", "PO Timeliness (detail)"],
      metrics: [
        "Timely Shipper Booking Submission (~0.02% not on-time)",
        "Timely SI/VGM Submit (~47% not on-time)",
        "Timely Container Loading Result (~35% not on-time)",
        "Timely Upload Shipping Document (~35% not on-time)",
        "Milestone On-Time Ratio (trend)",
      ],
      visuals: ["Four timeliness bars (% of total PO)", "Milestone On-Time Ratio line chart"],
      slicers: ["Supplier Name", "POL", "POD", "ATD Week"],
      granularity: "Supplier / PO-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "dimensions-analysis-pepco",
      name: "PEPCO Dimensions Analysis - Pepco",
      category: "Supplier",
      tier: 2,
      purpose: "Analysis of supplier-submitted carton / product dimensions.",
      granularity: "PO / item-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "milestone-resubmit-analysis",
      name: "PEPCO Milestone Resubmit Analysis",
      category: "Supplier",
      tier: 2,
      purpose: "Tracks supplier milestone resubmissions.",
      granularity: "PO / milestone-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "po-hod-analysis",
      name: "PEPCO PO HOD Analysis",
      category: "Supplier",
      tier: 2,
      purpose: "Analysis of PO handover dates (HOD).",
      granularity: "PO-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "po-milestone-changes",
      name: "PEPCO PO Milestone Changes",
      category: "Supplier",
      tier: 2,
      purpose: "Tracks changes to PO milestones over time.",
      granularity: "PO / milestone-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "supplier-user",
      name: "PEPCO Supplier User",
      category: "Supplier",
      tier: 3,
      purpose: "Supplier user access directory.",
      granularity: "User-level",
      calcBasis: "n/a",
      detailLevel: "structural",
      warning: "Likely contains personal data; catalogue structure only.",
    },

    /* ===================== CARRIER (10) ===================== */
    {
      id: "carrier-performance",
      name: "PEPCO Carrier Performance",
      category: "Carrier",
      tier: 1,
      purpose: "Carrier schedule integrity and transit-time performance.",
      pages: ["Schedule Integrity (Origin)", "Carrier Booked TEU Summary - Pepco", "Weekly Summary", "Scorecard"],
      metrics: ["Average Departure Delay (Days) = 1.82", "Average Arrival Delay (Days) = 5.81"],
      visuals: ["Booked vs Actual Transit Time chart", "KPI cards"],
      slicers: ["Carrier (CMDU, COSU, EGLV, HLCU, MAEU, MSCU)", "POL"],
      granularity: "Carrier / booking-level",
      calcBasis: "documented",
      calcDetail: "Departure Delay = ATD − Booked ETD; Arrival Delay = ATA − Booked ETA; averaged in days.",
      detailLevel: "full",
    },
    {
      id: "carrier-performance-pepco",
      name: "PEPCO Carrier Performance - Pepco",
      category: "Carrier",
      tier: 1,
      purpose: "Client-styled layout of Carrier Performance.",
      granularity: "Carrier / booking-level",
      calcBasis: "documented",
      detailLevel: "structural",
      variantOf: "carrier-performance",
    },
    {
      id: "carrier-scoring",
      name: "PEPCO Carrier Scoring",
      category: "Carrier",
      tier: 1,
      purpose: "Composite carrier scoring across reliability dimensions.",
      pages: ["Overview", "Carrier Scoring", "Glossary"],
      metrics: [
        "Ontime (0–10)",
        "Speed (0–10)",
        "Capacity, reliability and flexibility (0–10)",
        "Variability",
      ],
      visuals: ["Scoring table by carrier (TSHG, ONEY, MSCU, MAEU, HLCU, EGLV, COSU, CMDU)"],
      sampleData: "Totals: Ontime 6.24 / Speed 3.57 / Capacity 8.10 / Variability 2.22",
      slicers: ["ATD Year (2025, 2026)", "ATD Month (01–06)"],
      granularity: "Carrier-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "allocation-management",
      name: "PEPCO Allocation Management",
      category: "Carrier",
      tier: 2,
      purpose: "Carrier allocation planning and management.",
      granularity: "Allocation Week / carrier-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "free-time-preferred-routing",
      name: "PEPCO Free Time and Preferred Routing",
      category: "Carrier",
      tier: 2,
      purpose: "Free-time (detention / demurrage) and preferred routing analysis.",
      granularity: "Lane / carrier-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "procurement-report",
      name: "PEPCO Procurement Report",
      category: "Carrier",
      tier: 2,
      purpose: "Carrier procurement / rate analysis.",
      granularity: "Carrier / lane-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "transship-port-performance",
      name: "PEPCO Transship Port Performance",
      category: "Carrier",
      tier: 2,
      purpose: "Transshipment port performance analysis.",
      granularity: "Port / booking-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "transship-port-performance-pepco",
      name: "PEPCO Transship Port Performance - Pepco",
      category: "Carrier",
      tier: 2,
      purpose: "Client-styled layout of Transship Port Performance.",
      granularity: "Port / booking-level",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "transship-port-performance",
    },
    {
      id: "weekly-closing",
      name: "PEPCO Weekly Closing",
      category: "Carrier",
      tier: 2,
      purpose: "Weekly operational closing summary.",
      granularity: "Weekly",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "weekly-closing-pepco",
      name: "PEPCO Weekly Closing - Pepco",
      category: "Carrier",
      tier: 2,
      purpose: "Client-styled layout of Weekly Closing.",
      granularity: "Weekly",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "weekly-closing",
    },

    /* ===================== ASN (1) ===================== */
    {
      id: "outbound-asn-log",
      name: "PEPCO Outbound ASN Log",
      category: "ASN",
      tier: 3,
      purpose: "Advance Shipping Notice outbound log (raw extract).",
      granularity: "Shipment-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },

    /* ===================== OPERATIONS (43) ===================== */
    {
      id: "etd-eta-accuracy",
      name: "PEPCO ETD And ETA Accuracy",
      category: "Operations",
      tier: 1,
      purpose: "Measures accuracy of estimated vs actual departure / arrival.",
      pages: [
        "ETD-ETA Analysis",
        "Booked ETD-Booked ETA Analysis",
        "Booked ETA in the past",
        "ETD/ETA Measurement",
        "Before ATD monitor",
        "Glossary",
      ],
      metrics: [
        "Transit-day distribution (% of total carrier bookings)",
        "POL-ETA Check: Y 18.72% / N 81.28%",
        "POD-ETA Check: Y 7.27% / N 92.73%",
      ],
      visuals: ["Transit-day distribution buckets", "ETA check breakdowns"],
      tableColumns: ["Carrier Booking Ref", "POL", "POD", "Vessel", "Voyage", "ETD", "ETA", "ETD Allocation", "ETA Allocation"],
      slicers: ["Booking Status", "Turkey Shipment toggle"],
      granularity: "Carrier booking-level",
      calcBasis: "documented",
      detailLevel: "full",
    },
    {
      id: "sla-report",
      name: "PEPCO SLA Report",
      category: "Operations",
      tier: 1,
      purpose: "Service-level compliance across OHA and supplier KPIs.",
      pages: ["OHA KPI", "Supplier"],
      metrics: ["Color-coded compliance % by KPI category / metric / origin country"],
      visuals: ["Large KPI matrix (monthly + weekly columns), color-coded compliance %"],
      slicers: [],
      granularity: "KPI / origin-country-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "origin-kpi-report",
      name: "PEPCO Origin KPI Report",
      category: "Operations",
      tier: 1,
      purpose: "Origin-side milestone on-time performance across the pre-departure lifecycle.",
      pages: ["Overview", "Weekly Overview", "Monthly Overview", "Raw Data", "KPI Definitions", "Glossary"],
      metrics: [
        "Booking Validation on-time",
        "Transport Preassign on-time",
        "SO Release to Supplier on-time",
        "AHOD Update on-time",
        "ATD Confirmation on-time",
        "Vessel Departure Confirmation on-time",
      ],
      visuals: ["Six ONTIME / NOT-ONTIME donut charts"],
      slicers: ["ETD Year/Month", "Origin Point", "DC", "OHA", "SO Type"],
      granularity: "Origin / milestone-level",
      calcBasis: "documented",
      calcDetail:
        "On-Time = milestone completed within N working days of its trigger — Booking Validation within 1 working day of Shipper Booking; Transport Preassign within 1 working day of Booking Validation; SO Release to Supplier within 7 days after the booked slot; AHOD Update within 2 working days of actual AHOD; ATD Confirmation within 3 working days of actual ATD; Vessel Departure Confirmation within 2 days of actual ATD.",
      detailLevel: "full",
    },
    {
      id: "po-milestone-performance",
      name: "PEPCO PO Milestone Performance",
      category: "Operations",
      tier: 1,
      purpose: "PO milestone completion performance by origin country and supplier.",
      pages: [
        "Overview",
        "Overview 2",
        "CRD Submit",
        "Container Loading Result",
        "Dimensions",
        "Vessel Departure",
        "Shipper Booking",
        "Shipper Booking Validation",
        "Raw Data",
        "Glossary",
      ],
      metrics: [
        "When it was possible / urgent / overdue (counts)",
        "Total PO's",
        "On-Time %",
        "Avg Days Overdue Before Completion",
      ],
      visuals: [
        "Table by Country (BD, CN, IN, KE, KH, PK, TR, VN, Total)",
        "On-time pie",
        "Top 10 Impact Supplier table",
      ],
      slicers: ["Country", "Supplier", "Milestone"],
      granularity: "PO / milestone-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "predictive-eta",
      name: "PEPCO Predictive ETA",
      category: "Operations",
      tier: 1,
      purpose: "Predictive arrival estimates benchmarked against the carrier's ETD-based estimate.",
      pages: [
        "Overview",
        "Predictive ETA (Booking Level)",
        "Predictive ETA (Container Level)",
        "Predictive ETA",
        "Glossary",
      ],
      metrics: [
        "MAE — Mean Absolute Error (days, vs actual arrival)",
        "On-Time %",
        "Bias (signed mean error — early vs late tendency)",
      ],
      visuals: [
        "Milestone table with MAE / On-Time / Bias grouped under ETD and PETA (2025)",
        "On-Time % area chart comparing ETD, PETA(1) 2025, PETA(2) 2025",
      ],
      slicers: ["Lane", "Carrier", "POL", "POD", "ATD Week/Month", "Class"],
      granularity: "Booking / container-level",
      calcBasis: "inferred",
      calcDetail:
        "PETA models are predictive arrival estimates benchmarked against the carrier's original ETD-based estimate. Lower MAE + higher On-Time % + Bias near zero = better model.",
      detailLevel: "full",
    },
    {
      id: "predictive-eta-pepco",
      name: "PEPCO Predictive ETA - Pepco",
      category: "Operations",
      tier: 1,
      purpose: "Client-styled layout of Predictive ETA.",
      granularity: "Booking / container-level",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "predictive-eta",
    },
    {
      id: "container-utilization",
      name: "PEPCO Container Utilization",
      category: "Operations",
      tier: 1,
      purpose: "Container fill efficiency / utilization analysis.",
      pages: ["SI Overview", "SI Monthly Summary"],
      metrics: ["Container fill / utilization %"],
      visuals: ["Fill / utilization scatter", "Bar charts"],
      slicers: [],
      granularity: "Container-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "container-utilization-pepco",
      name: "PEPCO Container Utilization - Pepco",
      category: "Operations",
      tier: 1,
      purpose: "Client-styled layout of Container Utilization.",
      granularity: "Container-level",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "container-utilization",
    },
    {
      id: "emissions",
      name: "PEPCO Emissions",
      category: "Operations",
      tier: 2,
      purpose: "Container-level CO₂ emissions reporting.",
      pages: ["Summary", "Glossary"],
      metrics: ["CO₂ emissions per container"],
      visuals: ["Container-level CO₂ table"],
      tableColumns: [
        "Carrier Booking Ref",
        "Container No",
        "Container Type",
        "Carrier",
        "Mode of transport",
        "ATA at POD",
        "Date of delivery to DC",
        "Weight of goods (kg)",
        "Distance",
      ],
      slicers: [],
      granularity: "Container-level",
      calcBasis: "inferred",
      calcDetail: "Emissions ≈ weight × distance (GLEC-style emissions factor).",
      detailLevel: "full",
    },
    {
      id: "ahod-reason-code",
      name: "PEPCO AHOD Reason Code",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of adjusted-handover-date reason codes.",
      pages: ["Overview", "Rawdata", "Glossary"],
      metrics: ["Total PO's with AHOD Reason by HOD Month", "Reason code distribution (FCL / LCL)"],
      visuals: ["Bar by HOD Month", "FCL/LCL pie by reason code (CD1, CD2, FM02, FM03, S01, V02, V03, V05, V06)"],
      sampleData: "FCL: V03 = 77.91%",
      slicers: ["HOD Month", "Origin Country", "Origin Port", "SO Type", "ATD Month", "ATD Week"],
      granularity: "PO-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "booking-rejection-analysis",
      name: "PEPCO Booking Rejection Analysis",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of booking rejections over time.",
      pages: ["Summary", "PEPCO Rejection Analysis"],
      metrics: ["Total Rejection by Month"],
      visuals: ["Total Rejection by Month bar", "KPI cards"],
      slicers: [],
      granularity: "Booking-level",
      calcBasis: "inferred",
      detailLevel: "full",
    },
    {
      id: "crd-indc-date-analysis",
      name: "PEPCO CRD And In-DC Date Analysis",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of cargo ready dates vs in-DC arrival dates.",
      granularity: "PO / order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "crd-indc-date-analysis-pepco",
      name: "PEPCO CRD And In-DC Date Analysis - Pepco",
      category: "Operations",
      tier: 2,
      purpose: "Client-styled layout of CRD And In-DC Date Analysis.",
      granularity: "PO / order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "crd-indc-date-analysis",
    },
    {
      id: "early-arrival-analysis",
      name: "PEPCO Early Arrival Analysis",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of early-arriving shipments.",
      granularity: "Order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "early-arrival-analysis-container",
      name: "PEPCO Early Arrival Analysis - Container Level",
      category: "Operations",
      tier: 2,
      purpose: "Container-level view of early-arriving shipments.",
      granularity: "Container-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "historical-eta",
      name: "PEPCO Historical ETA",
      category: "Operations",
      tier: 2,
      purpose: "Historical ETA tracking.",
      granularity: "Booking-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "historical-eta-pepco",
      name: "PEPCO Historical ETA - Pepco",
      category: "Operations",
      tier: 2,
      purpose: "Client-styled layout of Historical ETA.",
      granularity: "Booking-level",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "historical-eta",
    },
    {
      id: "in-dc-date-eta",
      name: "PEPCO In DC Date-ETA",
      category: "Operations",
      tier: 2,
      purpose: "In-DC date vs ETA analysis.",
      granularity: "Order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "manual-approval-analysis",
      name: "PEPCO Manual Approval Analysis",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of manual approval events.",
      granularity: "PO / event-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "monthly-volume-analysis-origin",
      name: "PEPCO Monthly Volume Analysis - Origin",
      category: "Operations",
      tier: 2,
      purpose: "Monthly origin-level volume analysis.",
      granularity: "Origin / order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "monthly-volume-analysis-origin-pepco",
      name: "PEPCO Monthly Volume Analysis - Origin - Pepco",
      category: "Operations",
      tier: 2,
      purpose: "Client-styled layout of Monthly Volume Analysis - Origin.",
      granularity: "Origin / order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
      variantOf: "monthly-volume-analysis-origin",
    },
    {
      id: "po-change-analysis",
      name: "PEPCO PO Change Analysis",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of PO changes over time.",
      granularity: "PO-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "po-milestone",
      name: "PEPCO PO Milestone",
      category: "Operations",
      tier: 2,
      purpose: "PO milestone tracking.",
      granularity: "PO / milestone-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "scoring",
      name: "PEPCO Scoring",
      category: "Operations",
      tier: 2,
      purpose: "Composite scoring analysis.",
      granularity: "Order / entity-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "seasonal-promo-tracker",
      name: "PEPCO Seasonal Promo Tracker",
      category: "Operations",
      tier: 2,
      purpose: "Tracks seasonal / promotional volume and readiness.",
      granularity: "PO / order-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "special-categories",
      name: "PEPCO Special Categories",
      category: "Operations",
      tier: 2,
      purpose: "Analysis of special merchandise categories.",
      granularity: "PO / item-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "supplier-performance-tracking",
      name: "PEPCO Supplier Performance Tracking",
      category: "Operations",
      tier: 2,
      purpose: "Ongoing tracking of supplier performance.",
      granularity: "Supplier / PO-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "pending-po-monitoring",
      name: "PEPCO Pending PO Monitoring",
      category: "Operations",
      tier: 2,
      purpose: "Monitoring of pending POs.",
      granularity: "PO-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "pending-telex-monitor",
      name: "PEPCO Pending TELEX Monitor",
      category: "Operations",
      tier: 2,
      purpose: "Monitoring of pending TELEX release.",
      granularity: "Booking-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "oha-management-bd",
      name: "PEPCO OHA Management BD",
      category: "Operations",
      tier: 2,
      purpose: "Origin Handling Agent management — Bangladesh.",
      granularity: "OHA / origin-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "oha-management-in",
      name: "PEPCO OHA Management IN",
      category: "Operations",
      tier: 2,
      purpose: "Origin Handling Agent management — India.",
      granularity: "OHA / origin-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "oha-management-kh",
      name: "PEPCO OHA Management KH",
      category: "Operations",
      tier: 2,
      purpose: "Origin Handling Agent management — Cambodia.",
      granularity: "OHA / origin-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "oha-management-pk",
      name: "PEPCO OHA Management PK",
      category: "Operations",
      tier: 2,
      purpose: "Origin Handling Agent management — Pakistan.",
      granularity: "OHA / origin-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "oha-management-tr",
      name: "PEPCO OHA Management TR",
      category: "Operations",
      tier: 2,
      purpose: "Origin Handling Agent management — Turkey.",
      granularity: "OHA / origin-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "oha-management-vn",
      name: "PEPCO OHA Management VN",
      category: "Operations",
      tier: 2,
      purpose: "Origin Handling Agent management — Vietnam.",
      granularity: "OHA / origin-level",
      calcBasis: "inferred",
      detailLevel: "structural",
    },
    {
      id: "extract-po-list",
      name: "PEPCO Extract PO List",
      category: "Operations",
      tier: 3,
      purpose: "Raw PO list extract.",
      granularity: "PO-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },
    {
      id: "extract-po-list-pepco",
      name: "PEPCO Extract PO List - Pepco",
      category: "Operations",
      tier: 3,
      purpose: "Client-styled layout of Extract PO List.",
      granularity: "PO-level",
      calcBasis: "n/a",
      detailLevel: "structural",
      variantOf: "extract-po-list",
    },
    {
      id: "dimension-data-extract",
      name: "PEPCO Dimension Data Extract",
      category: "Operations",
      tier: 3,
      purpose: "Raw dimension data extract.",
      granularity: "Item-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },
    {
      id: "shipment-list",
      name: "PEPCO Shipment List",
      category: "Operations",
      tier: 3,
      purpose: "Raw shipment list extract.",
      granularity: "Shipment-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },
    {
      id: "monthly-container-list",
      name: "PEPCO Monthly Container List",
      category: "Operations",
      tier: 3,
      purpose: "Monthly container list extract.",
      granularity: "Container-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },
    {
      id: "monthly-container-list-pepco",
      name: "PEPCO Monthly Container List - Pepco",
      category: "Operations",
      tier: 3,
      purpose: "Client-styled layout of Monthly Container List.",
      granularity: "Container-level",
      calcBasis: "n/a",
      detailLevel: "structural",
      variantOf: "monthly-container-list",
    },
    {
      id: "freightower-transit-leg-extract",
      name: "PEPCO Freightower Transit Leg Extract",
      category: "Operations",
      tier: 3,
      purpose: "Raw transit-leg extract (Freightower).",
      granularity: "Transit-leg-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },
    {
      id: "pep5-report",
      name: "PEPCO PEP5 Report",
      category: "Operations",
      tier: 3,
      purpose: "PEP5 reference / admin extract.",
      granularity: "Reference-level",
      calcBasis: "n/a",
      detailLevel: "structural",
    },
  ],
};

/* --- helpers -------------------------------------------------------- */
MOOV.bi.reportById = function (id) {
  return MOOV.bi.reports.find((r) => r.id === id) || null;
};
MOOV.bi.countByTier = function (tier) {
  return MOOV.bi.reports.filter((r) => r.tier === tier).length;
};
MOOV.bi.countByCategory = function (cat) {
  return MOOV.bi.reports.filter((r) => r.category === cat).length;
};
